[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.build]
cmds = ["cd backend/resumebuilder && mvn -B -ntp clean package -DskipTests"]

[start]
cmd = "java -jar backend/resumebuilder/target/resumebuilder-0.0.1-SNAPSHOT.jar"
