[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.build]
cmds = ["cd backend/resumebuilder && chmod +x mvnw && ./mvnw clean package -DskipTests"]

[start]
cmd = "java -jar backend/resumebuilder/target/*.jar"
