[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.build]
dependsOn = ["setup"]
cmds = ["cd backend/resumebuilder && mvn clean package -DskipTests"]

[start]
cmd = "java -jar backend/resumebuilder/target/*.jar"
